apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: git-controller
  name: ocm-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-controller
  namespace: ocm-system
  labels:
    app: git-controller
spec:
  selector:
    matchLabels:
      app: git-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: git-controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --oci-registry-addr=registry.ocm-system.svc.cluster.local:5000
        image: open-component-model/git-controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: git-controller
      terminationGracePeriodSeconds: 10
