apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: controller
  newName: controller
  newTag: latest
- name: open-component-model/git-sync-controller
  newName: localhost:5001/open-component-model/git-sync-controller
  newTag: v0.0.1
