apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: open-component-model/git-controller
  newName: ghcr.io/open-component-model/git-controller
  newTag: v0.12.1

# Comment to disable HTTPS for the registry
patches:
- path: ./patches/add_root_certificates.yaml
