---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - delivery.ocm.software
  resources:
  - gitsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - gitsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - gitsyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - delivery.ocm.software
  resources:
  - ocmresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
