# permissions for end users to view syncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sync-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: git-controller
    app.kubernetes.io/part-of: git-controller
    app.kubernetes.io/managed-by: kustomize
  name: sync-viewer-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - syncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - syncs/status
  verbs:
  - get
