apiVersion: delivery.ocm.software/v1alpha1
kind: Sync
metadata:
  name: git-sample
  namespace: ocm-system
spec:
  branch: main
  commitTemplate:
    email: <email>
    message: "Update made from git-controller"
    name: Gergely Brautigam
  interval: 10m0s
  subPath: ./application/podinfo
  snapshotRef:
    name: ocm-test-snapshot
  repositoryRef:
    name: test-repositroy
