apiVersion: delivery.ocm.software/v1alpha1
kind: Sync
metadata:
  name: git-sample
  namespace: ocm-system
spec:
  authRef:
    name: git-secret
    namespace: ocm-system
  branch: main
  commitTemplate:
    email: <email>
    message: "Update made from git-controller"
    name: Gergely Brautigam
  interval: 10m0s
  subPath: ./application/podinfo
  url: https://github.com/Skarlso/test
  componentRef:
    name: ocm-test-component
    namespace: ocm-system
  snapshotRef:
    name: ocm-test-snapshot
    namespace: ocm-system
