apiVersion: delivery.ocm.software/v1alpha1
kind: OCMSnapshot
metadata:
  labels:
    app.kubernetes.io/name: ocmsnapshot
    app.kubernetes.io/instance: ocmsnapshot-sample
    app.kubernetes.io/part-of: git-sync-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: git-sync-controller
  name: ocmsnapshot-sample
spec:
  # TODO(user): Add fields here
