apiVersion: delivery.ocm.software/v1alpha1
kind: Snapshot
metadata:
  labels:
    app.kubernetes.io/name: snapshot
    app.kubernetes.io/instance: snapshot-sample
    app.kubernetes.io/part-of: git-sync-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: git-sync-controller
  name: snapshot-sample
spec:
  # TODO(user): Add fields here
