---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: git-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: git-controller-manager-role
subjects:
- kind: ServiceAccount
  name: git-controller
  namespace: ocm-system
